/*global dev*/

/*
app.config.js
-------------
This config contains configuration items that relate to the app itself as opposed to dev.config.js
which is used to configure the development environment.
 */

module.exports = {
    brand: 'Red Hot React',
    // This is the class that is applied to the <i> element placed next to the brand.
    // By default this is the font-awesome fire image which is drawn due to the classes fa & fa-fire
    brandIcon: 'fa fa-fire',
    // The base path used for routing. All paths generated by react-router will be prepended
    basePath: {
        // The base used for the development bundle that is generated during gulp watch
        dev: '/',
        // The base path used for the production bundle generated by calling gulp compile
        prod: '/red-hot-react/'
    }
};

