module.exports = {
    // Location of js/jsx
    scripts: 'scripts',
    // Main script
    entry: './scripts/app',
    // Location of stylesheets
    styles: {
        scss: 'styles/scss',
        sass: 'styles/sass',
        less: 'styles/less',
        css: 'styles/css'
    },
    // Location of specs.
    tests: '__tests__',
    // Output for compiled.
    bin: 'bin',
    // File extensions to look for
    ext: {
        js: ['js', 'jsx', 'react'],
        spec: ['js', 'jsx', 'react']
    },
    // Port on which we will serve the dev server (along with intermediate files generated by webpack)
    port: 3000,
    // (this is the actual port that runs the dev server, but webpack sort of hijacks it to serve intermediate files)
    webPackPort: 3001,
    // Open browser on watch?
    open: true
};